let databaseArray = [
    {
        Title: "Beguiling 22 Karat Yellow Gold Overlapping Bell Jhumkas",
        Description: "Enchanting 22 Karat yellow gold jhumkas with a textured circular base, holding a textured bell bead trail, adorned with 2 ball hangings at the bottom",
        Type: "Jhumka",
        Weight: "5.580g",
        Price: 36137.00,
        DiscountPrice: 36000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512216JHEABA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/512216JHEABA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Spellbinding Gold Jhumka Earrings",
        Description: "Brighten up your Traditional Wear look with these Graceful and Enchanting Gold Jhumka Earrings crafted in 22 Karat Yellow Gold.",
        Type: "Jhumka",
        Weight: "3.112g",
        Price: 45206.00,
        DiscountPrice: 45000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JDPABA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JDPABA00_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JDPABA00_3.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JDPABA00_4.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Radiant Traditional Jhumkas",
        Description: "Add a touch of traditional charm to your outfit with these jhumkas crafted in 22 karat yellow gold in high polish",
        Type: "Jhumka",
        Weight: "6.706g",
        Price: 43700.00,
        DiscountPrice: 43000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512314JIBABB00_1.jpg?impolicy=pqmed&imwidth=640"],
        Brand: 'Tanishq',
    },
    {
        Title: "Artistic Yellow Gold Tiered Floral Jhumkas",
        Description: "These radiant 22 Karat Gold Jhumkas feature a floral stud with angled petals suspending 2 bells with etched matte panels, ending in a long gold bead",
        Type: "Jhumka",
        Weight: "6.564g",
        Price: 44819.00,
        DiscountPrice: 44000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JCQABA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JCQABA00_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JCQABA00_3.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JCQABA00_4.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Delightful Yellow Gold Clover Jhumkas",
        Description: "These lovely 22 Karat Gold Jhumkas feature an etched, matte 3-petal stud suspending a bell with matte drops, roped frets and gold discs ending in a bead",
        Type: "Jhumka",
        Weight: "6.764g",
        Price: 20718.00,
        DiscountPrice: 20000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JDAAGA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JDAAGA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Traditional Yellow Gold Filigree Jhumkas",
        Description: "These classic 22 Karat Gold Jhumkas feature a teardrop stud lined with small discs suspending a filigree bell ending with roped rings and hanging beads",
        Type: "Jhumka",
        Weight: "8.232g",
        Price: 55017.00,
        DiscountPrice: 55000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JCVABA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JCVABA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Incandescent Yellow Gold Swan Jhumkas",
        Description: "These graceful 22 Karat yellow Gold Jhumkas feature a paisley lined filigree bell crowned by 2 carved swans and a roped disc suspended by a floral stud",
        Type: "Jhumka",
        Weight: "3.674g",
        Price: 24555.00,
        DiscountPrice: 24000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JDMAGA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JDMAGA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Avant-Garde Yellow Gold Carved Jhumkas",
        Description: "These grand 22 Karat Gold Jhumkas feature a carved stud shaped like an elongated mitre, suspending a waved bell with cutout bands ending in a teardrop",
        Type: "Jhumka",
        Weight: "4.728g",
        Price: 31476.00,
        DiscountPrice: 30000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JBGABA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JBGABA00_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JBGABA00_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Brilliant Yellow Gold Peacock Jhumkas",
        Description: "These grand 22 Karat Gold Jhumkas feature a carved peacock stud suspending a lantern-like bell adorned with cutout diamonds and discs, ending in a bead",
        Type: "Jhumka",
        Weight: "3.660g",
        Price: 24461.00,
        DiscountPrice: 24000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/515090JDHAGA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/515090JDHAGA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Splendid Gold Jhumka Earrings",
        Description: "Illuminate your occasion ensemble by pairing it with these Captivating Jhumka Earrings crafted in 22 Karat High Polish Yellow Gold.",
        Type: "Jhumka",
        Weight: "4.273g",
        Price: 27672.00,
        DiscountPrice: 27000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512216JHFABB00_1.jpg?impolicy=pqmed&imwidth=640"],
        Brand: 'Tanishq',
    },
    {
        Title: "Enchanting 18 Karat Yellow Gold And Pearl Geometric Drop Earrings",
        Description: "These quirky 18 Karat yellow gold earrings feature a geometric design with a pearl adorned at the centre and at the bottom",
        Type: "Drops",
        Weight: "3.021g",
        Price: 15673.00,
        DiscountPrice: 15000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500109DAAABAPL_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500109DAAABAPL_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500109DAAABAPL_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Traditional 22 Karat Gold And Multi Stone Drop Earrings",
        Description: "These traditional 22 Karat gold drops feature a stone-set gold bead encrusted crown suspending a studded, beaded triangle with hanging ball charms",
        Type: "Drops",
        Weight: "10.445g",
        Price: 66874.00,
        DiscountPrice: 66000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511183DQEABA40_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511183DQEABA40_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Exquisite 18 Karat Yellow Gold And Citrine Drops",
        Description: "A citrine stone is prong-set on a gold drop that's suspended by an O-ring from an inverted V post featuring jali work in these 18 Karat gold drops",
        Type: "Drops",
        Weight: "5.059g",
        Price: 26015.00,
        DiscountPrice: 25000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500859DBAABA31_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500859DBAABA31_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500859DBAABA31_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Alluring 22 Karat Gold And Ruby Floral Drop Earrings",
        Description: "These luxurious 22 Karat gold drops feature shimmering prong-set rubies in 2 burgeoning floral clusters, attached to a screw-back post fastening",
        Type: "Drops",
        Weight: "7.701g",
        Price: 54136.00,
        DiscountPrice: 53000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511182DVNABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511182DVNABA18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Nimaya Ruby Drop Earrings",
        Description: "Ruby Drop Earrings with Traditional Design crafted in 22 Karat Yellow Gold with glossy finish",
        Type: "Drops",
        Weight: "6.610g",
        Price: 47880.00,
        DiscountPrice: 46000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511183DQJABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511183DQJABA18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Eccentric 22 Karat Gold And Ruby Drop Earrings",
        Description: "These quirky 22 Karat gold drops features a hanging teardrop ruby suspended from 2 clusters of rubies attached to each other by 3 arcs of gold",
        Type: "Drops",
        Weight: "5.636g",
        Price: 38982.00,
        DiscountPrice: 37000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512814DPEABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/512814DPEABA18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Enthralling 22 Karat Gold And Ruby Floral Drop Earrings",
        Description: "These gorgeous 22 Karat gold drops feature prong-set rubies arranged in a floral design, with a delicate hanging teardrop ruby suspended by o-ring",
        Type: "Drops",
        Weight: "7.516g",
        Price: 54530.00,
        DiscountPrice: 53000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512814DPFABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/512814DPFABA18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Enrapturing 22 Karat Gold And Multi Stone Teardrop Earrings",
        Description: "These lovely 22 Karat gold drops feature 1 teardrop ruby set amidst round emeralds, and another hanging from an emerald nestled between 2 more rubies",
        Type: "Drops",
        Weight: "5.061g",
        Price: 35895.00,
        DiscountPrice: 35000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512814DPGABA40_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/512814DPGABA40_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Graceful 22 Karat Yellow Gold Lead Patterned Drop Earrings",
        Description: "These oh-so-lovely 22 Karat yellow gold earrings feature a long chain accented with Ruby studded leaves",
        Type: "Drops",
        Weight: "3.106g",
        Price: 23533.00,
        DiscountPrice: 23000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511096DCCABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511096DCCABA18_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511096DCCABA18_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Graceful 22 Karat Gold And Ruby Floral Drop Earrings",
        Description: "These lush 22 Karat gold drops feature 11 dazzling rubies in a floral design with 1 delicate ruby teardrop suspended from the tip of the flower",
        Type: "Drops",
        Weight: "3.116g",
        Price: 22913.00,
        DiscountPrice: 22000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511096DCGABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511096DCGABA18_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511096DCGABA18_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Luxurious 18 Karat Gold And Ruby Curved Stud",
        Description: "This luxurious pair of earrings feature 4 ruby-studs in a floral design attached to an 18 Karat gold stem with leaf detailing, truly setting it apart",
        Type: "Hoops",
        Weight: "3.610g",
        Price: 20997.00,
        DiscountPrice: 19000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500177HKAABA12_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500177HKAABA12_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500177HKAABA12_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Dainty Beaded Gold Hoop Earrings",
        Description: "Add the classic sheen of gold to your outfit and look stunning with this pair of hoop earrings crafted in 18 Karat Yellow Gold.",
        Type: "Hoops",
        Weight: "1.266g",
        Price: 6976.00,
        DiscountPrice: 6000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/503013HZHAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/503013HZHAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/503013HZHAAA00_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Sublime Gold Hoop Earrings",
        Description: "Add charm to your everyday look with this sublime pair of gold hoops crafted in 18 Karat Yellow Gold.",
        Type: "Hoops",
        Weight: "0.545g",
        Price: 2899.00,
        DiscountPrice: 2700.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/502218HDSAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/502218HDSAAA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Dainty Delicate Gold Hoop Earrings",
        Description: "Make a subtle style statement with these delicate hoop earrings crafted in 18 Karat Yellow Gold with a glossy finish.",
        Type: "Hoops",
        Weight: "1.286g",
        Price: 6760.00,
        DiscountPrice: 6700.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/503013HZGAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/503013HZGAAA00_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/503013HZGAAA00_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Timeless 18 Karat Yellow Gold Bali-Style Hoop Earrings",
        Description: "These 18 Karat gold earrings feature two rings and a multi-faceted gold bead with tiny dots all over it strung on a smooth, easy-on-hinged gold hoop",
        Type: "Hoops",
        Weight: "0.966g",
        Price: 5139.00,
        DiscountPrice: 5000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/502218HDUAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/502218HDUAAA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Delightful Gold Hoop Earrings",
        Description: "Add a touch of glam to your sublime look with these Geometric Hoop Earrings Crafted in 22 Karat High Polish Yellow Gold suitable for any occasion.",
        Type: "Hoops",
        Weight: "4.077g",
        Price: 23868.00,
        DiscountPrice: 22000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511418HAYAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511418HAYAAA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Entrancing Swirling Gold Beaded Hoop Bali Earrings",
        Description: "The mesmerising swirling mesh pattern in these floral hoop earrings crafted in 18 Karat Yellow Gold makes this an enchanting pair.",
        Type: "Hoops",
        Weight: "3.608g",
        Price: 20035.00,
        DiscountPrice: 19000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/501720HCSAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/501720HCSAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/501720HCSAAA00_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Elegant Gold Hoop Bali Earrings",
        Description: "Revel in Minimalistic glory with these Hoop Earrings Crafted in 22 Karat Glossy Yellow Gold. Comes in a fine glossy finish.",
        Type: "Hoops",
        Weight: "5.66g",
        Price: 33171.00,
        DiscountPrice: 32000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/510340HDAAKA00.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/510340HDAAKA00_1.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/510340HDAAKA00_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/510340HDAAKA00_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Romantic Gold Hoop Earrings",
        Description: "Romanticise every moment of your life with the subtle sheen of these hoop earrings crafted in 18 Karat Yellow Gold.",
        Type: "Hoops",
        Weight: "1.597g",
        Price: 8496.00,
        DiscountPrice: 8000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/502218HOVAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/502218HOVAAA00_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/502218HOVAAA00_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Sophisticated Yellow Gold Thunderbolt Hoop Earrings",
        Description: "These suave 18 Karat Yellow Gold Hoops feature a polished 3-pronged zigzag with a hanging teardrop, suspended by o-ring from a flattened hook",
        Type: "Hoops",
        Weight: "3.466g",
        Price: 19100.00,
        DiscountPrice: 18000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500937HBAAAA00_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500937HBAAAA00_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Hypnotic Ruby Floral Round Stud Earrings",
        Description: "These spiral floral stud earrings have been crafted in 22 Karat Yellow Gold and studded with rubies.",
        Type: "Studs",
        Weight: "8.921g",
        Price: 63040.00,
        DiscountPrice: 62000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512814SQEABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/512814SQEABA18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Charming 22 Karat Yellow Gold And Ruby Floral Stud Earrings",
        Description: "These riveting 22 Karat gold studs feature 4 oval and 5 round prong-set rubies arranged in a charmingly classic flower design, with a screw-back post",
        Type: "Studs",
        Weight: "5.096g",
        Price: 37106.00,
        DiscountPrice: 36000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511183STSABB18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511183STSABB18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Charming 18 Karat Yellow Gold And Pearl Stud Earrings",
        Description: "Graceful 18 Karat yellow gold studs featuring 3 stems flaunting a swirl pattern and holding a pearl at the bottom",
        Type: "Studs",
        Weight: "2.356g",
        Price: 11700.00,
        DiscountPrice: 11000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500060SAAAGAPL_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500060SAAAGAPL_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500060SAAAGAPL_3.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Resplendent Floral Ruby Stud Earrings",
        Description: "Floral Stud Earrings set in 22 Karat Yellow Gold and studded with Marquise and Round Rubies",
        Type: "Studs",
        Weight: "5.942g",
        Price: 42912.00,
        DiscountPrice: 42000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511183SSFABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511183SSFABA18_1.jpg?impolicy=pqmed&imwidth=640"],
        Brand: 'Tanishq',
    },
    {
        Title: "Mesmerizing 22 Karat Gold And Ruby Bloom Stud Earrings",
        Description: "These glamorous 22 Karat gold studs feature 9 lush prong-set marquise rubies tipped in gold, encircling 1 round ruby in a blooming flower design",
        Type: "Studs",
        Weight: "4.117g",
        Price: 29012.00,
        DiscountPrice: 28000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/512814SQUABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/512814SQUABA18_2.jpg?impolicy=pqmed&imwidth=640"],
        Brand: 'Tanishq',
    },
    {
        Title: "Appealing 18 Karat Yellow Gold Ruby-Embellished Petals Stud Earrings",
        Description: "Awe-striking 18 Karat yellow gold studs featuring a flower design with 6 petals and a bud, all embellished with Rubies",
        Type: "Studs",
        Weight: "1.693g",
        Price: 11160.00,
        DiscountPrice: 11000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500067SWAABA12_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500067SWAABA12_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Minimalist 18 Karat Yellow Gold And Pearl Studs",
        Description: "A true mark of understated elegance, these 18 Karat gold studs feature a luminous pearl attached to the gold post and a Bombay screw back",
        Type: "Studs",
        Weight: "1.693g",
        Price: 9348.00,
        DiscountPrice: 9000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/500104SHAABAPL_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500104SHAABAPL_2.jpg?impolicy=pqmedlow&imwidth=320",
            "https://staticimg.titan.co.in/Tanishq/Catalog/500104SHAABAPL_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Classy 18 Karat Yellow Gold And Pearl Swirling Petals Stud Earrings",
        Description: "Impressive 18 Karat yellow gold studs featuring a flower design with swirling petals and a pearl-adorned bud",
        Type: "Studs",
        Weight: "5.449g",
        Price: 24247.00,
        DiscountPrice: 24000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/501033SXKABAPL_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/501033SXKABAPL_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Resplendent Floral Ruby Stud Earrings",
        Description: "Floral Stud Earrings set in 22 Karat Yellow Gold and studded with Marquise and Round Rubies",
        Type: "Studs",
        Weight: "5.942g",
        Price: 42912.00,
        DiscountPrice: 42000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/511183SSFABA18_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/511183SSFABA18_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    },
    {
        Title: "Opulent 18 Karat Gold And Emerald Paisley Drop Earrings",
        Description: "These 18 Karat gold drop earrings feature lush emeralds clustered in a twisted paisley motif, with a single dangling emerald teardrop",
        Type: "Studs",
        Weight: "5.611g",
        Price: 38081.00,
        DiscountPrice: 37000.00,
        Img: ["https://staticimg.titan.co.in/Tanishq/Catalog/501095SAJABA11_1.jpg?impolicy=pqmed&imwidth=640",
            "https://staticimg.titan.co.in/Tanishq/Catalog/501095SAJABA11_2.jpg?impolicy=pqmedlow&imwidth=320"],
        Brand: 'Tanishq',
    }
]

localStorage.setItem("database",JSON.stringify(databaseArray));